// Make a run, and the people in it.
//
// This is how a private or fixed run starts. The main evergreen log is public
// and self-serve; it needs only its host seeded here.
//
//   node seed/seed.js --run beyond-belief --name "Beyond Belief" \
//     --fixed 2026-09-15 --days 35 \
//     --weeks "Curiosity,Care,Responsibility,Play,Rest" \
//     --host "John <john@spacetobe.xyz>" \
//     --person "Sam Okafor <sam@example.com> Europe/London" \
//     --person "Priya R <priya@example.com> Asia/Kolkata"
//
//   node seed/seed.js --run practice --name "The Practice Log" --evergreen --public \
//     --host "John <john@spacetobe.xyz> Europe/Lisbon"
//
// It prints SQL on stdout and the magic links on stderr, so the links can be
// read while the SQL is piped somewhere:
//
//   node seed/seed.js … > /tmp/seed.sql
//   npx wrangler d1 execute practice-log --local --file=/tmp/seed.sql
//
// LINK_KEY must be the same value the Worker has, or the links it later emails
// will not be the links printed here.

import { mintToken } from '../src/auth.js';

const args = process.argv.slice(2);
const one = (name, fallback = null) => {
  const i = args.indexOf(`--${name}`);
  return i > -1 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : fallback;
};
const many = (name) => args.reduce((acc, a, i) => (a === `--${name}` && args[i + 1] ? [...acc, args[i + 1]] : acc), []);
const flag = (name) => args.includes(`--${name}`);

const env = { LINK_KEY: process.env.LINK_KEY };
if (!env.LINK_KEY) {
  console.error('LINK_KEY is not set.\n  export LINK_KEY="$(openssl rand -base64 32)"   # keep it, the Worker needs the same one');
  process.exit(1);
}

const appUrl = process.env.APP_URL || 'https://spacetobe.xyz/log/';

const slug = one('run');
const name = one('name', slug);
const evergreen = flag('evergreen');
const startsOn = one('fixed');
const days = Number(one('days', '0'));
const weeks = one('weeks');
const standfirst = one('standfirst');
const publicJoin = flag('public');

// The room: how many places, what people are joining, when it meets, and
// what the contribution page suggests. All optional; a run with no places has
// no limit and no roster arithmetic.
const places = one('places');
const blurb = one('blurb', DEFAULT_BLURB());
const meets = one('meets');
// A range, not a figure: --suggest 150-300. Offered only if someone asks.
const suggest = one('suggest');
const suggestPair = suggest ? suggest.split('-').map(function (n) { return Math.round(Number(n.trim()) * 100); }) : [];

function DEFAULT_BLURB() {
  // John's own words for what a Sit is. Overridable per run with --blurb.
  return 'A Sit runs as a shared experiment over a set stretch of days. We each sit in our own '
    + 'lives, knowing that others are sitting the same days, and meet live once a week.\n\n'
    + 'John hosts and teaches. The practices are rooted in contemplative traditions and he won’t '
    + 'pretend otherwise — but this is a lineage of feeling, not a body of doctrine. Nothing is '
    + 'asked of you as belief.';
}

if (!slug) fail('--run <slug> is required');
if (!evergreen && !startsOn) fail('either --evergreen or --fixed YYYY-MM-DD');
if (publicJoin && !evergreen) fail('--public is only valid with --evergreen');
if (startsOn && !/^\d{4}-\d{2}-\d{2}$/.test(startsOn)) fail('--fixed wants YYYY-MM-DD');
if (startsOn && !(days > 0)) fail('--days is required with --fixed');

function fail(msg) { console.error(msg); process.exit(1); }

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

const lines = [
  '-- generated by seed/seed.js — review before running',
  'PRAGMA foreign_keys = ON;',
  '',
  `INSERT INTO run (slug, name, mode, public_join, starts_on, length_days, week_labels, standfirst,`,
  `                 places, blurb, meets, suggest_low, suggest_high)`,
  `VALUES (${q(slug)}, ${q(name)}, ${q(evergreen ? 'evergreen' : 'fixed')}, ${publicJoin ? 1 : 0}, ` +
    `${startsOn ? q(startsOn) : 'NULL'}, ${days || 'NULL'}, ` +
    `${weeks ? q(JSON.stringify(weeks.split(',').map((s) => s.trim()).filter(Boolean))) : 'NULL'}, ` +
    `${q(standfirst)}, ${places ? Number(places) : 'NULL'}, ${q(blurb)}, ${q(meets)}, ` +
    `${suggestPair[0] || 'NULL'}, ${suggestPair[1] || 'NULL'})`,
  `ON CONFLICT (slug) DO UPDATE SET name = excluded.name, mode = excluded.mode, public_join = excluded.public_join,`,
  `  starts_on = excluded.starts_on, length_days = excluded.length_days,`,
  `  week_labels = excluded.week_labels, standfirst = excluded.standfirst,`,
  `  places = excluded.places, blurb = excluded.blurb, meets = excluded.meets,`,
  `  suggest_low = excluded.suggest_low, suggest_high = excluded.suggest_high;`,
  '',
];

// Evergreen counts each person's days from the day they joined; a fixed run
// counts everyone's from its own start. Either way this is the anchor.
const joinedDefault = evergreen ? today() : startsOn;

const entries = [
  ...many('host').map((s) => ({ raw: s, host: true })),
  ...many('person').map((s) => ({ raw: s, host: false })),
];

if (!entries.length) console.error('note: no --person given, so this makes an empty run');

const links = [];
for (const entry of entries) {
  const m = /^(.*?)<([^>]+)>\s*(\S+)?\s*(\d{4}-\d{2}-\d{2})?\s*$/.exec(entry.raw);
  if (!m) fail(`could not read --person ${entry.raw}\n  wanted: "Name <email> [Timezone] [joined-on]"`);

  const personName = m[1].trim() || m[2].split('@')[0];
  const email = m[2].trim().toLowerCase();
  const tz = m[3] || 'Europe/London';
  const joined = m[4] || joinedDefault;

  const { token, token_hash, token_enc } = await mintToken(env);

  // Seeding is John putting someone in directly, so the place is already
  // taken — no invitation to accept. The invite path is for the mutual yes.
  lines.push(
    `INSERT INTO person (run_id, name, email, timezone, token_hash, token_enc, is_host,`,
    `                    joined_on, took_place_at)`,
    `SELECT id, ${q(personName)}, ${q(email)}, ${q(tz)}, ${q(token_hash)}, ${q(token_enc)}, ` +
      `${entry.host ? 1 : 0}, ${q(joined)}, unixepoch() FROM run WHERE slug = ${q(slug)}`,
    `ON CONFLICT (run_id, email) DO UPDATE SET`,
    `  name = excluded.name, timezone = excluded.timezone,`,
    `  token_hash = excluded.token_hash, token_enc = excluded.token_enc,`,
    `  token_issued_at = unixepoch(),`,
    `  took_place_at = COALESCE(person.took_place_at, unixepoch());`,
    '',
  );

  links.push(`${entry.host ? '[host] ' : ''}${personName} <${email}>  ${tz}\n  ${appUrl}?t=${encodeURIComponent(token)}`);

}

console.log(lines.join('\n'));

console.error('\n' + '─'.repeat(72));
console.error('Links. Each one is a login — send it to its own person and nowhere else.');
console.error('Re-running this replaces the token, and the old link stops working.');
console.error('─'.repeat(72));
for (const l of links) console.error(l);
console.error('');

function today() {
  return new Date().toISOString().slice(0, 10);
}
