// Build the log into one file at /log/index.html.
//
// The site's own six slugs are generated by build/build_shell.py from a design
// bundle. This is deliberately a separate build with a separate output: the log
// owns /log/** and touches nothing else, so re-running the site generator must
// never come back dirty because of it.
//
//   node practice-log/app/build.js [--api https://…]
//
// The API origin is baked in at build time rather than fetched, so the app has
// no configuration request to make before it can paint.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');

const DEFAULT_API = 'https://practice-log.beingsclub.workers.dev';

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};

const api = arg('api', process.env.PRACTICE_LOG_API || DEFAULT_API).replace(/\/+$/, '');
const css = readFileSync(join(here, 'app.css'), 'utf8');
const shell = readFileSync(join(here, 'shell.html'), 'utf8');

// Nothing committed can be secret — the repo is public and GitHub Pages serves
// it byte for byte. The API origin is a public address; a key would not be.
const SUSPECT = [/sk-[A-Za-z0-9]{16}/, /re_[A-Za-z0-9]{16}/, /RESEND/, /LINK_KEY/];

function page({ script, out, title }) {
  const js = readFileSync(join(here, script), 'utf8').replace('__API_ORIGIN__', api);
  if (js.includes('__API_ORIGIN__')) throw new Error('API origin placeholder not replaced');

  const html = shell
    .replace('<title>Practice Log · Space to Be</title>', `<title>${title}</title>`)
    .replace('/*__CSS__*/', () => css.trim())
    .replace('/*__JS__*/', () => js.trim());

  for (const s of SUSPECT) {
    if (s.test(html)) throw new Error(`refusing to write a build containing ${s}`);
  }

  const path = join(repo, ...out);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, html);
  console.log(`${(html.length / 1024).toFixed(1).padStart(6)}KB  ${path}`);
}

page({ script: 'app.js', out: ['log', 'index.html'], title: 'Practice Log · Space to Be' });
page({ script: 'host.js', out: ['log', 'host', 'index.html'], title: 'Host · Practice Log' });

console.log(`   api  ${api}`);
